name: Dreams
favicon: null
layout_spectrum: 0.96407
typography_spectrum: 0.09095
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#69c0d6'
    - '#004459'
    - '#009bba'
    - '#5a6669'
  brandStrength: 0.5
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
